### ISSUE TITLE
Specify a field type mongodbAiidprodTaxa.field_list.placeholder Node field

### ISSUE THREAD

**Issue by cesarvarela** [PartnershipOnAI/aiid#218]
Will deal with this:

```
If you know all field types in advance, the best strategy is to explicitly define them with the `createTypes` action, and skip inference with the `@dontInfer` directive.
See https://www.gatsbyjs.org/docs/actions/#createTypes
mongodbAiidprodTaxa.field_list.default:
 - type: boolean
   value: false
 - type: string
   value: 'global'
mongodbAiidprodTaxa.field_list.placeholder:
 - type: boolean
   value: false
 - type: string
   value: 'Select name here'
```

How to do it: https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization/#fixing-field-types
